### ISSUE TITLE
Create New User Form - Align GPS fields

### ISSUE THREAD

**Issue by isaacanip** [ePareto-Information-System/SORMAS-Project#16]
The input GPS boxes and its associated labels must be well spaced.
![image](https://user-images.githubusercontent.com/60930711/151939142-91547fb1-b3bb-44b7-bd96-f9b27b9f883d.png)

**Comment by faatihi** [comment]
Looks like the form's design has changed. New look:
![image](https://user-images.githubusercontent.com/1176692/156549504-b63481f8-24bb-44a9-817d-0a20f72eed38.png)

I suggest we space the fields evenly across and keep them closer together since they're related.

![image](https://user-images.githubusercontent.com/1176692/156550929-dc5b52d1-4a35-4a70-9b80-1095cdcef919.png)

**Comment by isaacanip** [comment]
15.12.2022
UAT done on for v1.74.3
